// Importing the createSlice function from Redux Toolkit to create a slice for meal selection
import { createSlice } from '@reduxjs/toolkit';

// Defining the mealsSlice
export const mealsSlice = createSlice({
  name: 'meals',
  initialState: [
    { name: 'Breakfast', cost: 50, selected: false },
    { name: 'High Tea', cost: 25, selected: false },
    { name: 'Lunch', cost: 65, selected: false },
    { name: 'Dinner', cost: 70, selected: false },
  ],

  // Reducers to handle actions related to meals selection
  reducers: {
    toggleMealSelection: (state, action) => {
      state[action.payload].selected = !state[action.payload].selected;
    },
  },
});

// Exporting the action generated by createSlice
export const { toggleMealSelection } = mealsSlice.actions;

export default mealsSlice.reducer;
